---
title: "Examine landscape-scale DGS outputs"
author: "Melissa Lucash"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    
    This script pulls in the total biomass and THU maps 
    and then summarizes biomass per THU at an annual timestep in a csv file.
    Need to reproject the maps first and only use the total biomass maps
---

Note: Cache is set to true in the setup chunk because this can take a little while to run. 

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.width = 14, cache = T, fig.height = 16, autodep = T)
library(ggplot2)
library(raster)
library(rgdal)
library(tidyverse)
library(plyr)
library(png)
library(dplyr) #this interacts with tidyverse
library(grid)
library(gridExtra)
source("add_datetime.R")

#model_dir <-"D:/Lucash/ResearchAssistantProfessor/Alaska_Reburns_Project/Sims_DGS_methods_paper/Jan_2022_Sims/"

model_dir<-"C:/Users/mlucash/Alaska_Reburns_Project_Sims/"

#historical_sim_dir <-paste0(model_dir,"/Calib_Landscape_Scrapple_220119A/")

historical_sim_dir <-paste0(model_dir,"Calib_Landscape_Scrapple_230302A/")

scenario_type<-"Historical"
offsetYear<-(-20) #Historical

scenario_type<-"ClimateChange"
offsetYear<-1 #CC

year1 <- 1990
date<-Sys.Date()

Scenario_LUT <- read.csv (paste0(model_dir,"Scenarios_DGS_Paper.csv"))
full_scen_list<-(Scenario_LUT[c(36:40),1]) #historical
full_scen_list<-(Scenario_LUT[c(31:35),1]) #climate change

length_sim<-50  #50 year sim

output_dir<-paste0(model_dir, "Output_Sims_DGS_methods_paper/ByTHU/")
```

First, read in all the biomass and THU maps, then summarize them

```{r plot liquid}

#SOM_values_time1<-as.vector(raster(paste0(historical_sim_dir,"DGS_rp/SOMTC-1.img")))#species raster

full_matrix<-NULL
  for (t in 1:length(full_scen_list)){#for every scenario
  each_scenario<-full_scen_list[t]
  thu_dir<-paste(model_dir,each_scenario,"/DGS_rp/", sep="") #directory of reprojected biomass raster
  all_files<-list.files(thu_dir) #total biomass file.
  no_xml <-  Filter(function(x) grepl("img$", x), all_files) #SOM maps
  SOM_maps <-  Filter(function(x) grepl("SOMTC", x), no_xml) #SOM maps
  THU_maps <-  Filter(function(x) grepl("THU", x), no_xml) #THU maps
  
  #biomass_matrix<-NULL
  for (s in 1:length_sim){#for every time step
    each_thu_year<-THU_maps[s]
    each_som_year<-SOM_maps[s]
    thu_values<-as.vector(raster(paste(thu_dir,each_thu_year,sep="")))#thu raster 
    som_values<-as.vector(raster(paste(thu_dir,each_som_year,sep="")))#biomass raster       
    row<-cbind.data.frame(each_scenario,s, thu_values, som_values)#cbind all the maps together. 
    full_matrix<-rbind.data.frame(full_matrix, row)#cbind all the maps together. 
  }
  }#end of species loop  
  colnames(full_matrix)<-c("Scenario", "Time","THU","SOM")
  
  thus <- read_csv(paste0(historical_sim_dir, "SHAW/interiorAK_THUs-Burn-new2-adjSlope.csv")) %>% 
  slice(-1:-2) %>% 
  filter(!is.na(THUName))
  
  som_matrix_joined<-left_join(full_matrix, thus[c(1,4,5)], by=c("THU"="THUNumber"))
  som_matrix_joined$ActualYear<-som_matrix_joined$Time + year1-1
  som_matrix_activeCells<-subset(som_matrix_joined, som_matrix_joined$SOM>0)


  all_data_ddply<-ddply(som_matrix_activeCells, .(ActualYear, VegetationType1), summarize,
                       mean_SOM = mean(SOM),
                       SD_SOM = sd(SOM),
                       SE_SOM = sd(SOM)/sqrt(length(SOM)))
  
  all_data_means<-subset(all_data_ddply,all_data_ddply$VegetationType1!="NA")
  all_data_means$Scenario<-rep(scenario_type, times=nrow(all_data_means))

write.csv(all_data_means, file=paste0(output_dir,scenario_type, "-AGB_by_THU.csv"))

########### Now make the graphs from the csv files.   ####################

Historical<-read.csv(file=paste0(output_dir,"Historical-AGB_by_THU.csv"))
ClimateChange<-read.csv(file=paste0(output_dir,"ClimateChange-AGB_by_THU.csv"))

all_data_scenarios<-rbind.data.frame(Historical, ClimateChange)

all_data_scenarios$Scenario <- factor(all_data_scenarios$Scenario, levels = c("Historical", "ClimateChange"))

plt.cols.short <- c("grey30", "darkorange") #Number corresponds to scenarios
legend_title<-'Climate Scenarios'

png_name<-paste0(output_dir, "SOM_Carbon_byTHU", date, ".png", sep="")
#png(filename=png_name, width = 5, height = 4, units = 'in', res = 300)

carbon_byTHU<-ggplot(all_data_scenarios, aes(x=(ActualYear), y=mean_SOM, group=Scenario)) +
  geom_line(aes(x=(ActualYear), y=mean_SOM, colour=Scenario))+
  geom_ribbon(aes(ymin=(mean_SOM)-(SE_SOM), ymax=(mean_SOM)+(SE_SOM), colour=Scenario), alpha=0.25, show.legend = FALSE)+   scale_color_manual(values = plt.cols.short) +
  scale_fill_manual(values = plt.cols.short)+
  #theme_classic()+xlab(NULL)+ylab("Aboveground biomass (g/m2)") + theme(legend.position = "right")+
  theme_classic()+xlab(NULL)+ylab(expression(Soil~carbon~(gC/m^2))) + theme(legend.position = "none")+
  scale_x_continuous(breaks=seq(1990, 2040, 10), limits=c(1990, 2042))+
  scale_y_continuous(breaks=seq(0, 20000, 2000), limits=c(0, 20000))+
  facet_wrap(~ VegetationType1)
ggsave(filename=png_name, plot = carbon_byTHU, width = 5,  height = 4, units = "in",  dpi = 300)

dev.off()



```

